### ISSUE TITLE
V2.0.0 (Coming Soon!)

### ISSUE THREAD

**Issue by toxisco** [michelelacorte/IPTVFree#4]
Salve,

Quando uscira v2.0.0 (Coming Soon!) ?

Sto facendo alcuni test..pero mi piacerebbe sapere quando sara pubblicata..

Grazie

**Comment by michelelacorte** [comment]
Salve,

Stiamo lavorando, non le so dare una data precisa, rimanga su questa pagina per ulteriori aggiornamenti.

La prego di non aprire nuove issue, se le serve qualche informazione ci può contattare via email
